substitutions:
  output_name_1: "Output 1"
  output_name_2: "Output 2"
  input_name_1: "Input 1"
  input_name_2: "Input 2"

packages:

  shelly-plus-2: !include ../../hardware/shelly-plus-2.yaml

  logger: !include ../../common/logger.yaml
  
  reset: !include ../../common/reset.yaml
  
  time: !include ../../common/time.yaml
  
  web-server: !include ../../common/web-server.yaml
  
  mqtt: !include ../../common/mqtt.yaml
  
  sun: !include ../../common/sun.yaml
  
  halt_automations: !include ../../packages/halt-automations.yaml

  wifi: !include 
    file: ../../common/wifi.yaml
    vars:
      static_ip: ${static_ip}

  shutter: !include
    file: shutter.yaml