substitutions:
  device_name: "poc-timbre"
  friendly_name: "poc-timbre"
  output_name_1: "Output 1"
  input_name_1: "Input 1"

packages:
  shelly-plus-1: !include hardware/shelly-plus-1.yaml
  halt-automations: !include packages/halt-automations.yaml
  logger: !include common/logger.yaml
  reset: !include common/reset.yaml
  web-server: !include common/web-server.yaml
  mqtt: !include common/mqtt.yaml
  wifi: !include
    file: common/wifi.yaml
    vars:
      static_ip: 10.0.20.31

globals:
  - id: ring_active
    type: bool
    restore_value: false
    initial_value: "false"

script:
  - id: ring_sound
    mode: restart
    then:
      - switch.turn_on: relay
      - delay: 0.5s
      - switch.turn_off: relay
      - delay: 0.5s
      - switch.turn_on: relay
      - delay: 0.5s
      - switch.turn_off: relay
      - delay: 10s

mqtt:
  topic_prefix: "${topic_prefix}"
  on_message:
    - topic: "zigbee2mqtt/laia-marc-porta-garatge-contact-sensor"
      qos: 1
      then:
        - lambda: |-
            if (id(halt_automations)) {
              ESP_LOGI("MQTT", "Automations are halted, ignoring door sensor event.");
              return;
            }

            StaticJsonDocument<256> doc;
            auto error = deserializeJson(doc, x);
            if (error) {
              ESP_LOGW("MQTT", "Failed to parse JSON: %s", error.c_str());
              return;
            }

            if (!doc.containsKey("contact")) {
              ESP_LOGW("MQTT", "Missing 'contact' key in JSON payload");
              return;
            }

            bool door_open = !doc["contact"].as<bool>();
            auto now = id(sntp_time).now();

            if (door_open && now.hour >= 21) {
              if (!id(effect_active)) {  // Only toggle if not already active
                ESP_LOGI("MQTT", "Garage door opened after 21:00, starting ring.");
                id(ring_active) = true;
                id(ring_sound).execute();
              }
            } else {
              if (id(effect_active)) {  // Only toggle if not already inactive
                ESP_LOGI("MQTT", "Garage door closed, stopping ring.");
                id(ring_active) = false;
              }
            }

    - topic: "${topic_prefix}/enable"
      qos: 1
      then:
        - globals.set:
            id: ring_active
            value: "true"
        - script.execute: ring_sound

    - topic: "${topic_prefix}/disable"
      qos: 1
      then:
        - globals.set:
            id: ring_active
            value: "false"
