substitutions:
  device_name: "llum-ambient-dormitori"
  device_id: "llum_ambient_dormitori"
  friendly_name: "Llum Ambient Dormitori"
  topic_prefix: "llum_ambient_dormitori"

esphome:
  name: ${device_name}

esp8266:
  board: esp01_1m

packages:
  # shelly-rgbw2: !include
  #   file: hardware/shelly-rgbw2.yaml
  #   vars:
  #     device_name: ${device_name}
  #     friendly_name: ${friendly_name}
  #
  wifi: !include
    file: common/wifi.yaml
    vars:
      device_name: ${device_name}

  # logger: !include common/logger.yaml
  web-server: !include common/web-server.yaml
  reset: !include common/reset.yaml
  # mqtt: !include common/mqtt.yaml
  time: !include common/time.yaml
 
logger:

light:
  - platform: monochromatic
    name: ${device_id}_ch1
    id: ${device_id}_ch1
    output: ${device_id}_out_ch1
  - platform: monochromatic
    name: ${device_id}_ch2
    id: ${device_id}_ch2
    output: ${device_id}_out_ch2
  - platform: monochromatic
    name: ${device_id}_ch3
    id: ${device_id}_ch3
    output: ${device_id}_out_ch3
  - platform: monochromatic
    name: ${device_id}_ch4
    id: ${device_id}_ch4
    output: ${device_id}_out_ch4
# Example output entry
output:
  - platform: esp8266_pwm
    id: ${device_id}_out_ch1
    pin: GPIO12
    frequency: 1000 Hz
  - platform: esp8266_pwm
    id: ${device_id}_out_ch2
    pin: GPIO15
    frequency: 1000 Hz
  - platform: esp8266_pwm
    id: ${device_id}_out_ch3
    pin: GPIO14
    frequency: 1000 Hz
  - platform: esp8266_pwm
    id: ${device_id}_out_ch4
    pin: GPIO4
    frequency: 1000 Hz

binary_sensor:
  - platform: gpio
    pin: GPIO5
    id: light_0_touch
    on_click:
      then:
        - if:
            condition:
              - light.is_off: ${device_id}_ch1
              - light.is_off: ${device_id}_ch2
              - light.is_off: ${device_id}_ch3
              - light.is_off: ${device_id}_ch4
            then:
              - light.turn_on:
                  id: ${device_id}_ch1
                  brightness: 1.0
              - light.turn_on:
                  id: ${device_id}_ch2
                  brightness: 1.0
              - light.turn_on:
                  id: ${device_id}_ch3
                  brightness: 1.0
              - light.turn_on:
                  id: ${device_id}_ch4
                  brightness: 1.0
            else:
              - light.turn_off: ${device_id}_ch1
              - light.turn_off: ${device_id}_ch2
              - light.turn_off: ${device_id}_ch3
              - light.turn_off: ${device_id}_ch4
    on_press:
      then:
        - if:
            condition:
              light.is_off: ${device_id}_ch1
            then:
              - delay: 0.5s
              - while:
                  condition:
                    binary_sensor.is_on: light_0_touch
                  then:
                    - light.dim_relative:
                        id: ${device_id}_ch1
                        relative_brightness: 5%
                        transition_length: 0.1s
                    - delay: 0.1s
                    - light.dim_relative:
                        id: ${device_id}_ch2
                        relative_brightness: 5%
                        transition_length: 0.1s
                    - delay: 0.1s
                    - light.dim_relative:
                        id: ${device_id}_ch3
                        relative_brightness: 5%
                        transition_length: 0.1s
                    - delay: 0.1s
                    - light.dim_relative:
                        id: ${device_id}_ch4
                        relative_brightness: 5%
                        transition_length: 0.1s
                    - delay: 0.1s
            else:
              - delay: 0.5s
              - while:
                  condition:
                    and:
                      - binary_sensor.is_on: light_0_touch
                      - light.is_on: ${device_id}_ch1
                  then:
                    - light.dim_relative:
                        id: ${device_id}_ch1
                        relative_brightness: -5%
                        transition_length: 0.1s
                    - delay: 0.1s
                    - light.dim_relative:
                        id: ${device_id}_ch2
                        relative_brightness: -5%
                        transition_length: 0.1s
                    - delay: 0.1s
                    - light.dim_relative:
                        id: ${device_id}_ch3
                        relative_brightness: -5%
                        transition_length: 0.1s
                    - delay: 0.1s
                    - light.dim_relative:
                        id: ${device_id}_ch4
                        relative_brightness: -5%
                        transition_length: 0.1s
                    - delay: 0.1s
