esphome:
  name: llum-ventilador-dormitori
  friendly_name: llum-ventilador-dormitori

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "qwJIq1t/XmqjXd+FpZeT2erKfBxFl3lHdWvjlwQufHQ="

ota:
  - platform: esphome
    password: "3a693a83d84ed0a073031a67f5dc0896"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Llum-Ventilador-Dormitori"
    password: "GvJ1B6YTJ5Yp"

captive_portal:
    