substitutions:
  device_name: "llum-escala"
  friendly_name: "llum-escala"
  static_ip: "10.0.20.33"
  topic_prefix: "llum_escala"

packages:
  shelly-plus-1: !include
    file: hardware/shelly-plus-1.yaml
    vars:
      device_name: ${device_name}
      friendly_name: ${friendly_name}

  wifi: !include
    file: common/wifi.yaml
    vars:
      static_ip: ${static_ip}

  debug: !include common/debug.yaml
  reset: !include common/reset.yaml
  time: !include common/time.yaml
  web-server: !include common/web-server.yaml
  mqtt: !include common/mqtt.yaml
  sun: !include common/sun.yaml

# Auto-off script to turn off the light after 5 minutes
script:
  - id: auto_off_5min
    mode: restart
    then:
      - delay: 5min
      - switch.turn_off: relay

binary_sensor:
  - platform: gpio
    name: "${device_name} Switch"
    pin: GPIO4
    filters:
      - delayed_on_off: 50ms

    on_press:
      - logger.log: "${device_name} Button - PRESS"
      - switch.toggle: relay
      - if:
          condition:
            switch.is_on: relay
          then:
            - script.execute: auto_off_5min

mqtt:
  on_message:
    - topic: "${topic_prefix}/auto_trigger"
      qos: 0
      then:
        - if:
            condition:
              sun.is_below_horizon:
            then:
              - logger.log: "${device_name} auto trigger - nighttime, turning on light"
              - switch.turn_on: relay
              - script.execute: auto_off_5min
            else:
              - logger.log: "${device_name} auto trigger - daytime, ignoring"
