substitutions:
  device_name: "llum-cuina"
  friendly_name: "llum-cuina"
  static_ip: "10.0.20.34"
  topic_prefix: "llum_cuina"

packages:
  shelly-plus-rgbw-pm: !include 
    file: hardware/shelly-plus-rgbw-pm.yaml
    vars:
      device_name: ${device_name}
      friendly_name: ${friendly_name}

  wifi: !include 
    file: common/wifi.yaml
    vars:
      static_ip: ${static_ip}

  logger: !include common/logger.yaml
  #debug: !include common/debug.yaml
  reset: !include common/reset.yaml
  mqtt: !include common/mqtt.yaml
 
globals:
  # State machine
  - id: light_state
    type: int
    restore_value: false
    initial_value: "0"
  - id: in_transition
    type: bool
    restore_value: false
    initial_value: "false"

  # Color temperature control
  - id: brightness_cold_white
    type: float
    initial_value: "0.5" 
  - id: brightness_warm_white
    type: float
    initial_value: "1.0"

  # Pulse effect
  - id: pulse_active
    type: bool
    restore_value: false
    initial_value: "false"
  
mqtt:
  topic_prefix: "${topic_prefix}"
  on_message:
    - topic: "${topic_prefix}/toggle/llum_barra"
      qos: 1
      then:
        - script.execute: toggle_llum_barra
    - topic: "${topic_prefix}/toggle/llum_pica"
      qos: 1
      then:
        - script.execute: toggle_llum_pica
    - topic: "${topic_prefix}/brightness_cold_white"
      qos: 1
      then:
         - script.execute:
            id: set_brightness
            payload: !lambda 'return x;'
            target: !lambda 'return &id(brightness_cold_white);'  # Pass the pointer to the global variable
    - topic: "${topic_prefix}/brightness_warm_white"
      qos: 1
      then:
        - script.execute:
            id: set_brightness
            payload: !lambda 'return x;'
            target: !lambda 'return &id(brightness_warm_white);'  # Pass the pointer to the global variable
    - topic: "${topic_prefix}/toggle_strobe_effect"
      qos: 1
      then:
        - script.execute: toggle_strobe_effect

light:
  - platform: monochromatic
    id: llum_pica_r
    name: "Llum Pica Cold White"
    output: pwm_r
    restore_mode: ALWAYS_OFF
    default_transition_length: 0s
    effects:
      - strobe:
          name: "Strobe Effect Pica Cold White"
          colors:
            - state: True
              brightness: 100%
              duration: 500ms
            - state: False
              duration: 500ms

  - platform: monochromatic
    id: llum_pica_g
    name: "Llum Pica Warm White"
    output: pwm_g
    restore_mode: ALWAYS_OFF
    default_transition_length: 0s
    effects:
      - strobe:
          name: "Strobe Effect Pica Warm White"
          colors:
            - state: True
              brightness: 100%
              duration: 500ms
            - state: False
              duration: 500ms

  - platform: monochromatic
    id: llum_barra_b
    name: "Llum Barra Cold White"
    output: pwm_b
    restore_mode: ALWAYS_OFF
    default_transition_length: 0s
    effects:
      - strobe:
          name: "Strobe Effect Barra Cold White"
          colors:
            - state: True
              brightness: 100%
              duration: 500ms
            - state: False
              duration: 500ms

  - platform: monochromatic
    id: llum_barra_w
    name: "Llum Barra Warm White"
    output: pwm_w
    restore_mode: ALWAYS_OFF
    default_transition_length: 0s
    effects:
      - strobe:
          name: "Strobe Effect Barra Warm White"
          colors:
            - state: True
              brightness: 100%
              duration: 500ms
            - state: False
              duration: 500ms

binary_sensor:
  - platform: gpio
    id: interruptor_entrada_cuina
    name: "${device_name} Input 1"
    pin:
      number: GPIO36
      inverted: true
    filters:
      - delayed_on_off: 50ms
    on_state:
      then:
        - script.execute: cycle_lights
       
  - platform: gpio
    id: interruptor_barra
    name: "${device_name} Input 2"
    pin:
      number: GPIO37
      inverted: true
    filters:
      - delayed_on_off: 50ms
    on_state:
      then:
         - script.execute: cycle_lights

script:
  - id: toggle_llum_barra
    then: 
      if: 
        condition:
          and: 
            - light.is_off: llum_barra_b
            - light.is_off: llum_barra_w
        then:
          - light.turn_on: 
              id: llum_barra_b
              brightness: !lambda |-
                return id(brightness_cold_white);
          - light.turn_on: 
              id: llum_barra_w
              brightness: !lambda |-
                return id(brightness_warm_white);
        else:
          - light.turn_off: 
              id: llum_barra_b
              transition_length: 1s
          - light.turn_off: 
              id: llum_barra_w
              transition_length: 1s

  - id: toggle_llum_pica
    then: 
      if: 
        condition:
          and: 
            - light.is_off: llum_pica_r
            - light.is_off: llum_pica_g
        then:
          - light.turn_on: 
              id: llum_pica_r
              brightness: !lambda |-
                return id(brightness_cold_white);
          - light.turn_on: 
              id: llum_pica_g
              brightness: !lambda |-
                return id(brightness_warm_white);
        else:
          - light.turn_off: 
              id: llum_pica_r
              transition_length: 1s
          - light.turn_off: 
              id: llum_pica_g
              transition_length: 1s

  - id: cycle_lights
    then:
      - lambda: |-
          if (id(in_transition)) {
            ESP_LOGD("debug", "Transition in progress, ignoring input.");
            return;
          }
          id(in_transition) = true; // Block further transitions

          if (id(light_state) == 0) {
            ESP_LOGD("debug", "State 0: Turning ON llum_barra, Turning OFF llum_pica");
            id(toggle_llum_barra).execute(); // Turns on llum_barra
            id(light_state) = 1;
            id(in_transition) = false; // Allow transitions immediately
          } else if (id(light_state) == 1) {
            ESP_LOGD("debug", "State 1: Turning ON llum_pica, Keeping llum_barra ON");
            id(toggle_llum_pica).execute(); // Turns on llum_pica
            id(light_state) = 2;
            id(in_transition) = false; // Allow transitions immediately
          } else if (id(light_state) == 2) {
            ESP_LOGD("debug", "State 2: Turning OFF both llum_barra and llum_pica");
            id(toggle_llum_barra).execute(); // Turns off llum_barra
            id(toggle_llum_pica).execute(); // Turns off llum_pica
            id(wait_for_lights_off).execute();
          }

  - id: wait_for_lights_off
    then:
      - wait_until:
          condition:
            and:
              - light.is_off: llum_barra_b
              - light.is_off: llum_barra_w
              - light.is_off: llum_pica_r
              - light.is_off: llum_pica_g
          timeout: 2s
      - lambda: |-
          ESP_LOGD("debug", "All lights are off, wait_for_lights_off completed.");
          id(light_state) = 0;
          id(in_transition) = false; // Allow transitions

  - id: set_brightness
    parameters:
      payload: string    # The MQTT payload (JSON)
      target: float*     # A pointer to the target global variable
    then:
      - lambda: |-
          ESP_LOGD("MQTT", "Received payload: %s", payload.c_str());

          // Parse the JSON payload
          StaticJsonDocument<256> doc;
          auto error = deserializeJson(doc, payload);
          if (error) {
            ESP_LOGW("MQTT", "Failed to parse JSON: %s", error.c_str());
            return;
          }

          // Check if the JSON contains the "brightness" key
          if (doc.containsKey("brightness")) {
            float value = doc["brightness"].as<float>();
            *target = value;  // Set the value of the passed global variable
            ESP_LOGD("MQTT", "Set brightness to %f", value);
          } else {
            ESP_LOGW("MQTT", "Key 'brightness' not found in JSON payload");
          }

  - id: toggle_strobe_effect
    then:
      - if:
          condition:
            lambda: "return id(pulse_active);"  # Check if the strobe effect is active
          then:
            # Disable strobe effect
            - light.turn_on:
                id: llum_barra_b
                effect: none
                brightness: !lambda "return id(brightness_cold_white);"
            - light.turn_on:
                id: llum_barra_w
                effect: none
                brightness: !lambda "return id(brightness_warm_white);"
            - light.turn_on:
                id: llum_pica_r
                effect: none
                brightness: !lambda "return id(brightness_cold_white);"
            - light.turn_on:
                id: llum_pica_g
                effect: none
                brightness: !lambda "return id(brightness_warm_white);"
            - lambda: |-
                ESP_LOGD("Strobe Effect", "Disabling strobe effect");
                id(pulse_active) = false;

          else:
            # Enable strobe effect
            - light.turn_on:
                id: llum_barra_b
                effect: "Strobe Effect Barra Cold White"
            - light.turn_on:
                id: llum_barra_w
                effect: "Strobe Effect Barra Warm White"
            - light.turn_on:
                id: llum_pica_r
                effect: "Strobe Effect Pica Cold White"
            - light.turn_on:
                id: llum_pica_g
                effect: "Strobe Effect Pica Warm White"
            - lambda: |-
                ESP_LOGD("Strobe Effect", "Enabling strobe effect");
                id(pulse_active) = true;