substitutions:
  device_name: "llum-escala"
  friendly_name: "llum-escala"
  static_ip: "10.0.20.33"
  topic_prefix: "llum_escala"

packages:
  shelly-plus-1: !include 
    file: hardware/shelly-plus-1.yaml
    vars:
      device_name: ${device_name}
      friendly_name: ${friendly_name}

  wifi: !include 
    file: common/wifi.yaml
    vars:
      static_ip: ${static_ip}

  logger: !include common/logger.yaml
  reset: !include common/reset.yaml
  time: !include common/time.yaml
  web-server: !include common/web-server.yaml
  mqtt: !include common/mqtt.yaml

switch:
  - platform: output
    id: "relay"
    name: "${device_name} Relay"
    output: "relay_output"

binary_sensor:
  - platform: gpio
    name: "${device_name} Switch"
    pin: GPIO4
    id: light_button
    internal: true
    filters:
      - delayed_on_off: 50ms
    on_multi_click:

      # Single click (short press)
      - timing:
          - ON for at most 1s
        then:
          - logger.log: "${devicename} Button - TAP"
          - switch.turn_on: relay
          - delay: 2min
          - switch.turn_off: relay

      # Hold (long press)
      - timing:
          - ON for at least 1s
        then:
          - logger.log: "${devicename} Button - HOLD"
          - switch.turn_on: relay
          - delay: 30min
          - switch.turn_off: relay
