substitutions:
  device_name: "llum-cuina"
  friendly_name: "llum-cuina"
  static_ip: "10.0.20.34"
  topic_prefix: "llum_cuina"

packages:
  shelly-plus-rgbw-pm: !include 
    file: hardware/shelly-plus-rgbw-pm.yaml
    vars:
      device_name: ${device_name}
      friendly_name: ${friendly_name}

  wifi: !include 
    file: common/wifi.yaml
    vars:
      static_ip: ${static_ip}

  logger: !include common/logger.yaml
  reset: !include common/reset.yaml
  web-server: !include common/web-server.yaml
  # Beware when enabling this since if it cannot connect to the broker it will restart after 15 minutes
  # mqtt: !include common/mqtt.yaml

globals:
  - id: light_state
    type: int
    restore_value: false
    initial_value: "0"

light:
  - platform: cwww
    id: llum_pica 
    name: "Llum Pica"
    cold_white: pwm_r
    warm_white: pwm_g
    cold_white_color_temperature: 6000 K
    warm_white_color_temperature: 2700 K
    constant_brightness: true

  - platform: cwww
    name: "Llum Barra"
    id: llum_barra
    cold_white: pwm_b
    warm_white: pwm_w
    cold_white_color_temperature: 6000 K
    warm_white_color_temperature: 2700 K
    constant_brightness: true

# switch:
#   - platform: template
#     name: "Toggle Llums"
#     id: toggle_llums
#     turn_on_action:
#       - light.toggle: llum_pica
#       - light.toggle: llum_barra

#   - platform: template
#     name: "Toggle Llum Pica"
#     id: toggle_llum_pica
#     turn_on_action:
#       - light.toggle: llum_pica

#   - platform: template
#     name: "Toggle Llum Barra"
#     id: toggle_llum_barra
#     turn_on_action:
#       - light.toggle: llum_barra

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO36
      inverted: True
    name: ${device_name} Input 1
    filters:
      - delayed_on: 50ms
      - delayed_off: 50ms
    on_state:
      - script.execute: toggle_lights

  - platform: gpio
    pin:
      number: GPIO37
      inverted: True
    name: ${device_name} Input 2
    filters:
      - delayed_on: 50ms
      - delayed_off: 50ms
    on_state:
      - script.execute: toggle_lights

script:
  - id: toggle_lights
    then:
      - lambda: |-
          ESP_LOGD("test", "Script toggle_lights executed");
          if (id(light_state) == 0) {
            ESP_LOGD("debug", "State 0: Turning ON llum_barra, Turning OFF llum_pica");
            id(toggle_llum_pica).turn_on();
            id(llum_pica).turn_off();
            id(light_state) = 1;
          } else if (id(light_state) == 1) {
            ESP_LOGD("debug", "State 1: Turning ON llum_pica, Turning ON llum_barra");
            id(llum_pica).turn_on();
            id(llum_barra).turn_on();
            id(light_state) = 2;
          } else {
            ESP_LOGD("debug", "State 2: Turning OFF both llum_barra and llum_pica");
            id(llum_barra).turn_off();
            id(llum_pica).turn_off();
            id(light_state) = 0;
          }