esphome:
  name: llum-cuina
  friendly_name: llum-cuina

esp32:
  board: esp32dev
  framework:
    type: esp-idf

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
   # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Llum-cuina Fallback Hotspot"
    password: "SVIgLIql004N"

captive_portal:
logger:
api:
  encryption:
    key: "8SCZZUwgDq+auPECDGEXZpMykE2kYk3SCrWPTdgX8Q8="
ota:
  - platform: esphome
    password: "a4b2e3b9cf16d0aebf26c39b8aad8498"

light:
  - platform: rgbw
    name: ${device_name} Led Stip
    red: pwm_r
    green: pwm_g
    blue: pwm_b
    white: pwm_w
    effects:
      - random:
      - strobe:
      - flicker:

status_led:
  pin: GPIO14

output:
  - platform: ledc
    pin: GPIO25
    id: pwm_r
    frequency: 19531
  
  - platform: ledc
    pin: GPIO26
    id: pwm_g
    frequency: 19531

  - platform: ledc
    pin: GPIO27
    id: pwm_b
    frequency: 19531

  - platform: ledc
    pin: GPIO4
    id: pwm_w
    frequency: 19531

switch:
  - platform: output
    name: "White LED Strip 1"
    output: pwm_r
    id: white_led_strip_1
    
  - platform: output
    name: "White LED Strip 2"
    output: pwm_g
    id: white_led_strip_2

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO36
      inverted: True
    name: ${device_name} Input 1
    filters:
      - delayed_on_off: 10ms
    on_multi_click:
      # Short press - toggle relay and turn off after 2 min
      - timing:
          - ON for at most 1s
        then:
          - logger.log: "${device_name} Button - TAP"
          - switch.toggle: white_led_strip_1

      # Long press - toggle relay and turn off after 30 min
      - timing:
          - ON for at least 1s
        then:
          - logger.log: "${device_name} Button - HOLD"
          - switch.toggle: white_led_strip_2
  
  - platform: gpio
    pin:
      number: GPIO22
    name: ${device_name} Onboard Button
    filters:
      - delayed_on_off: 10ms

sensor:
  - platform: adc
    pin: GPIO33
    id: temp_analog_reading
    attenuation: 12db

  - platform: resistance
    sensor: temp_analog_reading
    id: temp_resistance_reading
    configuration: DOWNSTREAM
    resistor: 10kOhm

  - platform: ntc
    sensor: temp_resistance_reading
    name: ${device_name} Temperature
    calibration:
      b_constant: 3350
      reference_resistance: 10kOhm
      reference_temperature: 298.15K

  - platform: adc
    pin: GPIO34
    attenuation: 12db
    name: ${device_name} Voltage
    accuracy_decimals: 1
    filters:
      - multiply: 10.85

  - platform: adc
    pin: GPIO35
    attenuation: 12db
    name: ${device_name} Current
    accuracy_decimals: 2
    filters:
      - offset: -0.794
      - multiply: 16.13
    unit_of_measurement: A