esphome:
  name: persiana-dormitori
  friendly_name: persiana-dormitori

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "WL/qTmj/zcuKpOQMozZrqUGlFKPbz1agrnMrU3z6z8g="

ota:
  - platform: esphome
    password: "a359e0b625925bd5a1c1b6f3b44c76e1"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Persiana-Dormitori"
    password: "LJ776legueTq"

captive_portal:
    