
substitutions:
  device_name: "persiana-marc-nord"
  friendly_name: "persiana-marc-nord"
  output_name_1: "Output 1"
  output_name_2: "Output 2"
  input_name_1: "Input 1"
  input_name_2: "Input 2"

packages:

  shelly-plus-2: !include devices/shelly-plus-2.yaml
  logger: !include packages/common/logger.yaml
  reset: !include packages/common/reset.yaml
  time: !include packages/common/time.yaml
  web-server: !include packages/common/web-server.yaml
  mqtt: !include packages/common/mqtt.yaml
  sun: !include packages/common/sun.yaml

  wifi: !include 
    file: packages/common/wifi.yaml
    vars:
      static_ip: 10.0.20.24

  shutter: !include
    file: packages/shutter.yaml

  
