esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  # on_boot:
  #   - lambda: |-
  #       id(my_ota).set_auth_password("new password");

esp32:
  board: esp32dev
  framework:
    type: esp-idf

status_led:
  pin: GPIO14

output:
  - platform: ledc
    pin: GPIO25
    id: pwm_r
    frequency: 19531
  
  - platform: ledc
    pin: GPIO26
    id: pwm_g
    frequency: 19531

  - platform: ledc
    pin: GPIO27
    id: pwm_b
    frequency: 19531

  - platform: ledc
    pin: GPIO4
    id: pwm_w
    frequency: 19531

sensor:
  - platform: adc
    pin: GPIO33
    id: temp_analog_reading
    attenuation: 12db

  - platform: resistance
    sensor: temp_analog_reading
    id: temp_resistance_reading
    configuration: DOWNSTREAM
    resistor: 10kOhm

  - platform: ntc
    sensor: temp_resistance_reading
    name: ${device_name} Temperature
    calibration:
      b_constant: 3350
      reference_resistance: 10kOhm
      reference_temperature: 298.15K

  - platform: adc
    pin: GPIO34
    attenuation: 12db
    name: ${device_name} Voltage
    accuracy_decimals: 1
    filters:
      - multiply: 10.85

  - platform: adc
    pin: GPIO35
    attenuation: 12db
    name: ${device_name} Current
    accuracy_decimals: 2
    filters:
      - offset: -0.794
      - multiply: 16.13
    unit_of_measurement: A