substitutions:
  device_name: "llum-escala"
  friendly_name: "llum-escala"
  static_ip: "10.0.20.33"
  topic_prefix: "llum_escala"

packages:
  shelly-plus-1: !include 
    file: hardware/shelly-plus-1.yaml
    vars:
      device_name: ${device_name}
      friendly_name: ${friendly_name}

  wifi: !include 
    file: common/wifi.yaml
    vars:
      static_ip: ${static_ip}

  debug: !include common/debug.yaml
  reset: !include common/reset.yaml
  time: !include common/time.yaml
  web-server: !include common/web-server.yaml
  mqtt: !include common/mqtt.yaml

# We want to stop all running scripts when any other button is pressed
script:
  - id: auto_off_3min
    mode: restart
    then:
      - script.stop: auto_off_30min
      - delay: 3min
      - switch.turn_off: relay

  - id: auto_off_30min
    mode: restart
    then:
      - script.stop: auto_off_3min
      - delay: 30min
      - switch.turn_off: relay

binary_sensor:
  - platform: gpio
    name: "${device_name} Switch"
    pin: GPIO4
    filters:
      - delayed_on_off: 50ms

    on_multi_click:
      # Short press - toggle relay and turn off after 2 min
      - timing:
          - ON for at most 1s
        then:
          - logger.log: "${device_name} Button - TAP"
          - switch.toggle: relay
          - if:
              condition:
                switch.is_on: relay
              then:
                - script.execute: auto_off_3min

      # Long press - toggle relay and turn off after 30 min
      - timing:
          - ON for at least 1s
        then:
          - logger.log: "${device_name} Button - HOLD"
          - switch.toggle: relay
          - script.execute: auto_off_30min