substitutions:
  device_name: "llum-ventilador-menjador"
  device_id: "llum_ventilador_menjador"
  friendly_name: "Llum Ventilador Menjador"
  topic_prefix: "llum_ventilador_menjador"

packages:

  shelly-25: !include ../hardware/shelly-25.yaml
  wifi: !include
    file: ../common/wifi.yaml
    vars:
      device_name: ${device_name}

  mqtt: !include
    file: ../common/mqtt.yaml
    vars:
      device_name: ${device_name}

  logger: !include ../common/logger.yaml
  web-server: !include ../common/web-server.yaml
  reset: !include ../common/reset.yaml
  time: !include ../common/time.yaml

  halt-automations: !include
    file: ../packages/halt-automations.yaml

binary_sensor:

  # Main button with multi-click behavior for light/fan control
  - platform: template
    name: "${friendly_name} Main Button"
    id: "main_button"
    lambda: |-
      return id(input_a).state;
    filters:
      - delayed_on_off: 50ms
    on_multi_click:

      # Single click (short press) - toggle relay_a (light)
      - timing:
          - ON for at most 1s
        then:
          - logger.log: "${device_name} Button - Toggle Light"
          - switch.toggle: relay_a

      # Hold (long press) - toggle relay_b (fan) with auto-off
      - timing:
          - ON for at least 1s
        then:
          - logger.log: "${device_name} Button - Toggle Fan"
          - switch.toggle: relay_b
          - if:
              condition:
                switch.is_on: relay_b
              then:
                - delay: 20min
                - switch.turn_off: relay_b
    internal: true
