substitutions:
  device_name: "llum-ambient-dormitori"
  device_id: "llum_ambient_dormitori"
  friendly_name: "Llum Ambient Dormitori"
  topic_prefix: "llum_ambient_dormitori"

packages:
  shelly-rgbw2: !include
    file: ../hardware/shelly-rgbw2.yaml
    vars:
      device_name: ${device_name}
      friendly_name: ${friendly_name}

  wifi: !include
    file: ../common/wifi.yaml
    vars:
      device_name: ${device_name}

  mqtt: !include
    file: ../common/mqtt.yaml
    vars:
      device_name: ${device_name}

  logger: !include ../common/logger.yaml
  web-server: !include ../common/web-server.yaml
  reset: !include ../common/reset.yaml
  time: !include ../common/time.yaml

light:
  - platform: monochromatic
    name: ${device_name}_white
    id: ${device_id}_white
    output: pwm_w

binary_sensor:
  - platform: gpio
    pin: GPIO5
    id: light_0_touch
    on_release:
      then:
        - if:
            condition:
              light.is_off: ${device_id}_white
            then:
              - light.turn_on:
                  id: ${device_id}_white
                  brightness: 0.4
            else:
              - light.turn_off: ${device_id}_white
