# TODO: I don't like to have the IP specified in the device

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${device_name}
    password: !secret ap_password

  # reboot_timeout: 0s

  on_connect:
    - lambda: |-
        ESP_LOGD("debug", "----------------- Connected to WiFi!");
  on_disconnect:
    - lambda: |-
        ESP_LOGD("debug", "----------------- Disconnected from WiFi!");

captive_portal:

ota:
  - platform: esphome
    id: my_ota
    # password: "old_password"
    password: !secret ota_password

sensor:
  - platform: wifi_signal
    name: "WiFi Signal Strength"
    update_interval: 60s
